#ifndef TOKENTYPE_H
#define TOKENTYPE_H

enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, SEMICOLON, MINUS, PLUS, SLASH, STAR, PERCENT, AT, DOT,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,
    AMPERSAND_AMPERSAND, PIPE_PIPE,

    IDENTIFIER, STRING, NUMBER,

    FN, LET, IF, ELSE, WHILE, RETURN, PRINT, MODEL,
    TRUE, FALSE,

    END_OF_FILE
};

#endif 
